[   INFO] [2018-03-14 17:17:02,241] [23268] [HTMLReport.py(92)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:17:02,243] [19204] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,243] [840] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-14 17:17:02,244] [19204] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:17:02,244] [13428] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,245] [840] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:17:02,245] [19948] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,246] [13428] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:17:02,247] [23244] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,249] [19948] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:17:02,250] [19204] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[WARNING] [2018-03-14 17:17:02,250] [840] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,250] [13428] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,251] [23244] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:17:02,251] [19948] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,251] [19204] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [840] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [13428] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,252] [23244] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,254] [23244] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:17:02,255] [24440] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,255] [6064] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,255] [24440] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:17:02,255] [6064] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [24440] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [6064] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,256] [24440] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:17:02,258] [20780] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,258] [23892] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:17:02,259] [20780] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:17:02,259] [23892] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,260] [20780] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,260] [23892] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(129)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_upper (__main__.test_2th)	测试相等
Pass	test_bad_int (__main__.test_2th)	测试异常类型

[  ERROR] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(131)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:17:02,278] [23268] [HTMLReport.py(132)] - 
测试结束！
运行时间: 0:00:00.019954
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:18:04,923] [23688] [HTMLReport.py(92)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:18:04,923] [12324] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,924] [21440] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[  ERROR] [2018-03-14 17:18:04,924] [12324] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:18:04,925] [1912] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,925] [21440] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:18:04,926] [18456] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,927] [18192] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,928] [1912] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:18:04,928] [18456] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[WARNING] [2018-03-14 17:18:04,929] [21440] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,929] [18192] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:18:04,930] [1912] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,930] [18456] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:18:04,930] [12324] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [21440] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [18192] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,931] [1912] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,932] [12324] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,933] [18192] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:18:04,933] [24168] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,934] [24168] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:18:04,934] [14664] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,934] [24168] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,935] [14664] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,935] [24168] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,936] [14664] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:18:04,937] [13860] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [9096] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:18:04,938] [13860] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [13860] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:18:04,938] [9096] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,938] [9096] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:18:04,957] [23688] [HTMLReport.py(129)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:18:04,958] [23688] [HTMLReport.py(131)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Fail	test_fail (__main__.test_1th)	测试失败
Error	test_error (__main__.test_1th)	测试错误
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:18:04,958] [23688] [HTMLReport.py(132)] - 
测试结束！
运行时间: 0:00:00.016652
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:25:45,825] [5668] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:25:45,826] [11120] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-14 17:25:45,827] [11120] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:25:45,827] [6004] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,829] [8412] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,830] [2564] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,830] [6004] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:25:45,830] [8412] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:25:45,830] [19548] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,831] [2564] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[  ERROR] [2018-03-14 17:25:45,832] [11120] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,832] [8412] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,833] [19548] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:25:45,833] [2564] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,834] [11120] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,835] [8412] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,835] [19548] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[WARNING] [2018-03-14 17:25:45,835] [6004] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,836] [19548] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,837] [6004] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:25:45,838] [23592] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,838] [23592] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:25:45,839] [18092] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,839] [23592] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,839] [18092] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,840] [23592] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,840] [18092] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:25:45,841] [23596] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,842] [23288] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:25:45,842] [23596] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,843] [23596] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:25:45,843] [23288] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,844] [23288] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(131)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(133)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:25:45,870] [5668] [HTMLReport.py(134)] - 
测试结束！
运行时间: 0:00:00.019940
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[   INFO] [2018-03-14 17:28:46,735] [15604] [HTMLReport.py(94)] - 预计并发线程数：10
[   INFO] [2018-03-14 17:28:46,737] [19600] [Result.py(53)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-14 17:28:46,738] [19600] [HTMLReport_test.py(29)] - 测试错误
[   INFO] [2018-03-14 17:28:46,739] [21996] [Result.py(53)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,740] [808] [Result.py(53)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,740] [21996] [HTMLReport_test.py(34)] - 测试失败
[   INFO] [2018-03-14 17:28:46,740] [8340] [Result.py(53)] - 开始测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,741] [808] [HTMLReport_test.py(15)] - 测试isupper
[   INFO] [2018-03-14 17:28:46,742] [17788] [Result.py(53)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,743] [8340] [Result.py(47)] - 跳过测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,744] [808] [Result.py(70)] - 测试执行通过：test_isupper (__main__.test_1th)
[  ERROR] [2018-03-14 17:28:46,744] [19600] [Result.py(84)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,744] [17788] [HTMLReport_test.py(21)] - 测试split
[   INFO] [2018-03-14 17:28:46,745] [8340] [Result.py(57)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,745] [808] [Result.py(57)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,745] [19600] [Result.py(57)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,746] [17788] [Result.py(70)] - 测试执行通过：test_split (__main__.test_1th)
[WARNING] [2018-03-14 17:28:46,747] [21996] [Result.py(98)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,748] [17788] [Result.py(57)] - 测试结束：test_split (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,748] [21996] [Result.py(57)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-14 17:28:46,749] [17752] [Result.py(53)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,750] [17752] [HTMLReport_test.py(47)] - 测试异常类型
[   INFO] [2018-03-14 17:28:46,750] [22776] [Result.py(53)] - 开始测试：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,750] [17752] [Result.py(70)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [22776] [Result.py(70)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [17752] [Result.py(57)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,751] [22776] [Result.py(57)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-14 17:28:46,753] [21332] [Result.py(53)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,754] [21044] [Result.py(53)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:28:46,755] [21332] [Result.py(98)] - 测试未通过：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-14 17:28:46,755] [21044] [Result.py(98)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,755] [21332] [Result.py(57)] - 测试结束：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,755] [21044] [Result.py(57)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-14 17:28:46,784] [15604] [HTMLReport.py(131)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-14 17:28:46,784] [15604] [HTMLReport.py(133)] - 
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_fail (__main__.test_1th)	测试失败
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-14 17:28:46,785] [15604] [HTMLReport.py(134)] - 
测试结束！
运行时间: 0:00:00.023278
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
[  DEBUG] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(25)] - debug
[WARNING] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(26)] - warning
[   INFO] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(27)] - info
[  ERROR] [2018-03-14 17:28:53,403] [23052] [loggerTest.py(28)] - error
[   INFO] [2018-03-14 17:28:53,404] [5984] [loggerTest.py(12)] - worker 0 info
[   INFO] [2018-03-14 17:28:53,404] [6220] [loggerTest.py(12)] - worker 1 info
[  DEBUG] [2018-03-14 17:28:53,404] [5984] [loggerTest.py(13)] - worker 0 调试
[  DEBUG] [2018-03-14 17:28:53,404] [6220] [loggerTest.py(13)] - worker 1 调试
[WARNING] [2018-03-14 17:28:53,405] [5984] [loggerTest.py(14)] - worker 0 警告
[WARNING] [2018-03-14 17:28:53,405] [6220] [loggerTest.py(14)] - worker 1 警告
[  ERROR] [2018-03-14 17:28:53,405] [5984] [loggerTest.py(15)] - worker 0 错误
[  ERROR] [2018-03-14 17:28:53,405] [6220] [loggerTest.py(15)] - worker 1 错误
