[   INFO] [2018-03-19 13:40:37,664] [5460] [HTMLReport.py(100)] - 预计并发线程数：10
[   INFO] [2018-03-19 13:40:37,665] [12600] [Result.py(43)] - 开始测试：test_error (__main__.test_1th)
[  ERROR] [2018-03-19 13:40:37,666] [12600] [HTMLReport_test.py(31)] - 测试错误
[   INFO] [2018-03-19 13:40:37,666] [13024] [Result.py(43)] - 开始测试：test_fail (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,667] [13024] [HTMLReport_test.py(41)] - 测试失败
[   INFO] [2018-03-19 13:40:37,667] [11060] [Result.py(43)] - 开始测试：test_isupper (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,667] [11060] [HTMLReport_test.py(17)] - 测试isupper
[   INFO] [2018-03-19 13:40:37,668] [14508] [Result.py(43)] - 开始测试：test_skip (__main__.test_1th)
[WARNING] [2018-03-19 13:40:37,668] [13024] [Result.py(120)] - 测试未通过：test_fail (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,669] [11060] [Result.py(87)] - 测试执行通过：test_isupper (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,669] [16176] [Result.py(43)] - 开始测试：test_split (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,670] [14508] [Result.py(72)] - 跳过测试：test_skip (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,670] [13024] [Result.py(53)] - 测试结束：test_fail (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,670] [11060] [Result.py(53)] - 测试结束：test_isupper (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,670] [16176] [HTMLReport_test.py(23)] - 测试split
[   INFO] [2018-03-19 13:40:37,670] [14508] [Result.py(53)] - 测试结束：test_skip (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,671] [16176] [Result.py(87)] - 测试执行通过：test_split (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,672] [16176] [Result.py(53)] - 测试结束：test_split (__main__.test_1th)
[  ERROR] [2018-03-19 13:40:37,689] [12600] [Result.py(103)] - 测试产生错误：	test_error (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,689] [12600] [Result.py(53)] - 测试结束：test_error (__main__.test_1th)
[   INFO] [2018-03-19 13:40:37,690] [16524] [Result.py(43)] - 开始测试：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-19 13:40:37,690] [16524] [HTMLReport_test.py(54)] - 测试异常类型
[   INFO] [2018-03-19 13:40:37,691] [16524] [Result.py(87)] - 测试执行通过：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-19 13:40:37,691] [16524] [Result.py(53)] - 测试结束：test_bad_int (__main__.test_2th)
[   INFO] [2018-03-19 13:40:37,691] [16524] [Result.py(43)] - 开始测试：test_upper (__main__.test_2th)
[CRITICAL] [2018-03-19 13:40:37,691] [16524] [HTMLReport_test.py(59)] - 测试执行
[   INFO] [2018-03-19 13:40:37,692] [16524] [Result.py(87)] - 测试执行通过：test_upper (__main__.test_2th)
[   INFO] [2018-03-19 13:40:37,692] [16524] [Result.py(53)] - 测试结束：test_upper (__main__.test_2th)
[   INFO] [2018-03-19 13:40:37,692] [16704] [Result.py(43)] - 开始测试：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-19 13:40:37,693] [4608] [Result.py(43)] - 开始测试：test_True (__main__.test_第三个测试)
[WARNING] [2018-03-19 13:40:37,693] [16704] [Result.py(120)] - 测试未通过：test_False (__main__.test_第三个测试)
[   INFO] [2018-03-19 13:40:37,693] [16704] [Result.py(53)] - 测试结束：test_False (__main__.test_第三个测试)
[WARNING] [2018-03-19 13:40:37,694] [4608] [Result.py(120)] - 测试未通过：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-19 13:40:37,694] [4608] [Result.py(53)] - 测试结束：test_True (__main__.test_第三个测试)
[   INFO] [2018-03-19 13:40:37,694] [5460] [HTMLReport.py(127)] - 
Pass	test_isupper (__main__.test_1th)	测试isupper
Pass	test_split (__main__.test_1th)	测试split
Pass	test_bad_int (__main__.test_2th)	测试异常类型
Pass	test_upper (__main__.test_2th)	测试相等

[  ERROR] [2018-03-19 13:40:37,694] [5460] [HTMLReport.py(129)] - 
Fail	test_fail (__main__.test_1th)	测试失败
Skip	test_skip (__main__.test_1th)	测试跳过
Error	test_error (__main__.test_1th)	测试错误
Fail	test_False (__main__.test_第三个测试)	测试FALSE
Fail	test_True (__main__.test_第三个测试)	测试True

[   INFO] [2018-03-19 13:40:37,716] [5460] [HTMLReport.py(140)] - 
测试结束！
运行时间: 0:00:00.031943
共计执行用例数量：9
执行成功用例数量：4
执行失败用例数量：3
跳过执行用例数量：1
产生异常用例数量：1
